/*
 * la licence de ce projet est accorder 
 * a l'entreprise bbs benhaddou brother's software
 * marque deposer aupr�s des autorit�s responsable * 
 */
package CommerceApp;

import Adapters.JDBCAdapter;
import java.math.BigDecimal;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objects.Validation;
import util.FileProcess;
import util.Operation;

/**
 *
 * @author ahmed
 */
public class DeleteOperatorDialog extends OperatorDialog implements Validation{
    int idOperator;
    /**
     * Creates new form deleteOperatorDialog
     */
    public DeleteOperatorDialog(
            JFrame parent, 
            Operation op, 
            FileProcess pr,
            int row){
        super(parent, op, pr);
        initComponents();
        idOperator = row;
        updateDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteOperatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteOperatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteOperatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteOperatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteOperatorDialog dialog = new DeleteOperatorDialog(
                        new javax.swing.JFrame(),
                        Operation.PROVIDER,
                        FileProcess.DELETE,
                        35);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Override
    public void record() {
        String sql = "DELETE FROM " + operation.getTableName()
                + " WHERE ID=" + idOperator;
        int choix = JOptionPane.showConfirmDialog(this,
                "Voulez Vous supprimer");
        if (choix == JOptionPane.YES_OPTION){
            JDBCAdapter delete = JDBCAdapter.connect();
            delete.executeQuery(sql);
        }
    }

    private void updateDialog() {
        String query = "SELECT * FROM " + operation.getTableName();
        JDBCAdapter operator = JDBCAdapter.connect();
        operator.executeQuery(query);
        if (operator.getRowCount() != 0){
            id.setText(Integer.toString((int)operator.getValueAt(0, 0)));
            designation.setText((String)operator.getValueAt(0, 1));
            adresse.setText((String)operator.getValueAt(0, 2));
            wilaya.setText(Integer.toString((int)operator.getValueAt(0, 3)));
            nrc.setText((String)operator.getValueAt(0, 4));
            nfi.setText((String)operator.getValueAt(0, 5));
            nar.setText((String)operator.getValueAt(0, 6));
            tel1.setText((String)operator.getValueAt(0,7));
            tel2.setText((String)operator.getValueAt(0, 8));
            tel3.setText((String)operator.getValueAt(0, 9));
            fax.setText((String)operator.getValueAt(0, 10));
            email.setText((String)operator.getValueAt(0, 11));
            web.setText((String)operator.getValueAt(0, 12));
            BigDecimal bd =(BigDecimal)operator.getValueAt(0, 13);
            solde.setText(bd.toString());
            obs.setText((String)operator.getValueAt(0, 14));
        }else{
            JOptionPane.showMessageDialog(this, "la requête ne peut aboutir la recherche a échoué");
            System.out.println("this line is reached");
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
